### ISSUE TITLE
Provide  python wrapper

### ISSUE THREAD

**Issue by bertwesarg** [score-p/scorep_binding_python#10]
I would like to encourage to provide a wrapper to encapsulate the `python -m scorep` usage. The name should be straight forward just `scorep-python` (where 'python' is the same name as used to install the package, so it could also be `scorep-python2.7`). This wrapper can also set the PYTHONPATH, thus a user is not forced to set this before execution.

**Comment by bertwesarg** [comment]
> It might be even interesting to automatically set the environment variables needed by Score-P. Probably using parameter like
> 
> python -m scorep --trace --profile script.py

is this even possible, i.e., can you hook into the option parsing of `python` at all?

**Comment by AndreasGocht** [comment]
yes. This is what I am doing for example using `--mpi` . The `-m` flag simply tells python to execute the given module as a script:
From the manpage:
```
       -m module-name
              Searches sys.path for the named module and runs the corresponding .py file as a script.
```

Which means calling the tracing using python is similar (but not exactly the same) as calling:
```
./scorep.py --trace --profile
```

**Comment by AndreasGocht** [comment]
I changed the way the module is used in `scorep_5.0`. You can now specify

```
python -m scorep --thread=omp --mpp=mpi <whatever else scorep flag> <some script.py>
```

`python -m scorep` works similar to scorep-python, but is more flexible I think. Therefore, I prefer to leave it in this way.

Best,

Andreas
