### ISSUE TITLE
remove oa_phase

### ISSUE THREAD

**Issue by AndreasGocht** [score-p/scorep_binding_python#104]
They are not tested, and I am not sure if they currently work at all.

**Comment by NanoNabla** [comment]
I'm not use if this issue is intended but OnlineAccess and therefore `SCOREP_User_OaPhaseBegin` and `SCOREP_User_OaPhaseEnd` are removed in Score-P > 7.0.
This breaks building python bindings with current Score-P's development versions.

**Comment by AndreasGocht** [comment]
Thanks for the hint. They need to be removed. As far as I know, PTF is no longer maintained anyway.

Best,

Andreas Gocht.

**Comment by AndreasGocht** [comment]
Fixed. Thanks!
