### ISSUE TITLE
Fail pip install .

### ISSUE THREAD

**Issue by jungla88** [score-p/scorep_binding_python#11]
I have installed without problem scorep. I provided a valid scorep-config path in my bashrc. Pip still stuck in this error:

> parallella@parallella2: scorep_binding_python $ pip -v install .
Created temporary directory: /tmp/pip-ephem-wheel-cache-Mta2Ys
Created temporary directory: /tmp/pip-install-EhsDox
Processing /home/parallella/luca/scorep_binding_python
  Created temporary directory: /tmp/pip-req-build-97kNCv
  Running setup.py (path:/tmp/pip-req-build-97kNCv/setup.py) egg_info for package from file:///home/parallella/luca/scorep_binding_python
    Running command python setup.py egg_info
    /usr/bin/ld: /opt/scorep/lib/libscorep_adapter_opencl_event_linktime.a(libscorep_adapter_opencl_event_linktime_la-scorep_opencl_wrap.o): relocation R_ARM_THM_MOVW_ABS_NC against `scorep_measurement_phase' can not be used when making a shared object; recompile with -fPIC
    /opt/scorep/lib/libscorep_adapter_opencl_event_linktime.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    Cuda is not supported, building without cuda
    OpenCL is supported, building with OpenCL
    Cuda is not supported, building without cuda
    OpenCL is supported, building with OpenCL
    OpenMPI detected
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-97kNCv/setup.py", line 205, in <module>
        extra_postargs=linker_flags_mpi)
      File "/usr/lib/python2.7/distutils/unixccompiler.py", line 207, in link
        raise LinkError, msg
    distutils.errors.LinkError: command 'cc' failed with exit status 1
Cleaning up...
  Removing source in /tmp/pip-req-build-97kNCv
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-97kNCv/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/prepare.py", line 324, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/prepare.py", line 154, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/req_install.py", line 486, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-97kNCv/

Do I miss something?
I post my scorep summary file:

> parallella@parallella2: scorep-4.0 $ cat scorep.summary 
Configure command:
  ./configure                   

Configuration summary:
  Score-P 4.0:
    Platform:                   arm (auto detected)
    Cross compiling:            no (auto detected)
    Machine name:               ARM
    otf2 support:               yes, using internal
    opari2 support:             yes, using internal
    cubew support:              yes, using internal
    cubelib support:            yes, using internal
    SHMEM support:              no, platform not supported

    Score-P (backend):
      C99 compiler used:        gcc -std=gnu99
      Pthread support:          yes, using gcc -std=gnu99 -pthread 
      compiler constructor:     yes, using attribute syntax
      Platform:                 arm (provided)
      TLS support:              yes, using __thread
      PAPI support:             no
      metric perf support:      yes
      Unwinding support:        no, missing libunwind support
        libunwind support:      no
      Sampling support:         no
      getrusage support:        yes
      RUSAGE_THREAD support:    yes, using -D_GNU_SOURCE
      dlfcn support:            yes, using -ldl
      OpenCL support:           yes
        libOpenCL support:      yes, using -lOpenCL
      OTF2 features:
        SIONlib support:        no
      CUDA support:             no
        libcudart support:      no
        libcuda support:        no
        libcupti support:       no
        CUPTI async support:    no
        CUDA version >= 6.0:    no
      OpenACC support:          no
      OpenMP support:           yes, using -fopenmp
        OpenMP pomp_tpd:        yes
        OpenMP ancestry:        yes
      PDT support:              no
      Cobi support:             no
      Timer support:            yes, providing gettimeofday, clock_gettime(CLOCK_MONOTONIC_RAW)
        Timer CPPFLAGS:         -D_POSIX_C_SOURCE=199309L
      libbfd support:           no
      compiler instrumentation: yes, using nm
      Online access support:    yes
      Memory tracking support:  yes
      Compiler wrappers:        scorep-gcc scorep-g++ scorep-gfortran scorep-mpicc scorep-mpicxx scorep-mpif77 scorep-mpif90 
      User library wrappers support:
                                no

    Score-P (GCC plug-in):
      GCC plug-in support:      no, missing plug-in headers, please install

    Score-P (libwrap):
      Library wrapper support:  no, llvm-config not found

    Score-P (MPI backend):
      C99 compiler works:       yes, using mpicc -std=gnu99
      C++ compiler works:       yes, using mpicxx
      F77 compiler works:       yes, using mpif77
      F90 compiler works:       yes, using mpif90
      Library used for MPI:     
      TLS support:              yes, using __thread
      PAPI support:             no
      metric perf support:      yes
      Unwinding support:        no, missing libunwind support
        libunwind support:      no
      Sampling support:         no
      getrusage support:        yes
      RUSAGE_THREAD support:    yes, using -D_GNU_SOURCE
      dlfcn support:            yes, using -ldl
      OpenCL support:           yes
        libOpenCL support:      yes, using -lOpenCL
      CUDA support:             no
        libcudart support:      no
        libcuda support:        no
        libcupti support:       no
        CUPTI async support:    no
        CUDA version >= 6.0:    no
      OpenACC support:          no
      OpenMP support:           yes, using -fopenmp
        OpenMP pomp_tpd:        yes
        OpenMP ancestry:        yes
      PDT MPI instrumentation:  yes, if PDT available
      Timer support:            yes, providing gettimeofday, clock_gettime(CLOCK_MONOTONIC_RAW)
        Timer CPPFLAGS:         -D_POSIX_C_SOURCE=199309L
      libbfd support:           no
      compiler instrumentation: yes, using nm
      Online access support:    yes
      Memory tracking support:  yes
      User library wrappers support:
                                no

    Score-P (score):
      C compiler used:          gcc  -std=gnu99
      C++ compiler used:        g++
      cube c++ library support: yes, using internal

  CubeLib 4.4:
    Cube installed into:        /opt/scorep
    Platform:                   arm (auto detected)
    Cross compiling:            no (auto detected)
    cubelib-config:             /opt/scorep/bin
    For detailed information:   "/opt/scorep/bin/cubelib-config --help"
    Examples:                   /opt/scorep/share/doc/cubelib/example

    CubeLib (frontend):
      POSIX socket:             yes
      Networking:               yes
      Cube C++ Library:         yes
      Cube Tools:               yes
      Frontend zlib compression :
                                readonly
        zlib headers :          
        zlib library :            -lz
        Notice:                 Front end part of cube (c++ cube library, tools and GUI) can read compressed cube files, but
                                write only uncompressed cube files.
        zlib compression flags :
                                 -DFRONTEND_CUBE_COMPRESSED_READONLY=yes 
      Use R for cube_dump:      no
        Notice:                 R, Rscript, RInside and Rcpp are necessary
      Data loading strategy :   Keep all in memory, load on demand
      C++ compiler used:        g++
       Compiler flags used:      

  CubeW 4.4:
    Cube installed into:        /opt/scorep
    Platform:                   arm (auto detected)
    Cross compiling:            no (auto detected)
    cubew-config:               /opt/scorep/bin
    For detailed information:   "/opt/scorep/bin/cubew-config --help"
    Examples:                   /opt/scorep/share/doc/cubew/example

    CubeW (backend):
      zlib compression :        yes
        zlib headers :          
        zlib library :            -lz
        Notice:                 Cube (c-writer library) produces compressed cube report.(enabled via environment variable
                                CUBEW_ZLIB_COMPRESSION=true)
        zlib compression flags :
                                 -DBACKEND_CUBE_COMPRESSED=yes 
      Advanced memory handling :
                                no
      Internal memory tracking :
                                no
      Internal memory tracing : no
      C99 compiler used:        gcc -std=gnu99
      C++ compiler used:        g++
       Compiler flags used:     -g -O2
       Compiler cxxflags used:  -g -O2

  OPARI2 2.0.3:
    Platform:                   arm (provided)
    Cross compiling:            no (provided)

  OTF2 2.1.1:
    Platform:                   arm (provided)
    Cross compiling:            no (provided)

    OTF2 (backend):
      C99 compiler used:        gcc -std=gnu99
      SIONlib support:          no
      Entropy sources:          clock_gettime getpid sysinfo gethostid
      Python bindings support:  yes, using /usr/local/bin/python
      Running tests:            no
        Parallel tests:         yes

**Comment by AndreasGocht** [comment]
Can you please add `--enable-shared` to the configure command:

```
../configure --enable-shared
```

Please be sure to clean your build directory. If you did your build in the Score-P source folder, you might need to delete this, and extract it again.

Best,

Andreas

**Comment by jungla88** [comment]
Reconfiguring and make install with --enable-shared(in configure of course) gives me now the following error in make install:

> /home/parallella/luca/scorep-4.0/build/build-mpi/libtool: line 10568: mpif77: command not found
libtool:   error: error: relink 'libscorep_adapter_mpi_event.la' with the above command before installing it
Makefile:2504: recipe for target 'install-libLTLIBRARIES' failed
make[4]: *** [install-libLTLIBRARIES] Error 1
make[4]: Leaving directory '/home/parallella/luca/scorep-4.0/build/build-mpi'
Makefile:4816: recipe for target 'install-am' failed
make[3]: *** [install-am] Error 2
make[3]: Leaving directory '/home/parallella/luca/scorep-4.0/build/build-mpi'
Makefile:4810: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/home/parallella/luca/scorep-4.0/build/build-mpi'
Makefile:732: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/parallella/luca/scorep-4.0/build'
Makefile:1026: recipe for target 'install' failed
make: *** [install] Error 2

I had not report it previously with the simple ../configure.
I also tried to force configuration with:

> $ ../configure --enable-shared --with-mpi=openmpi --with-nocross-compiler-suite=gcc

But the same error occurs.
Clearly I have a fully working OpenMPI 3.0.1 version whose mpif77 works fine

Hoping that this is usefull to the comprehension, I append here my ompi_info output and info from my mpif77:

> parallella@parallella2: bin $ ompi_info
                 Package: Open MPI parallella@parallella2 Distribution
                Open MPI: 3.0.1
  Open MPI repo revision: v3.0.1
   Open MPI release date: Mar 29, 2018
                Open RTE: 3.0.1
  Open RTE repo revision: v3.0.1
   Open RTE release date: Mar 29, 2018
                    OPAL: 3.0.1
      OPAL repo revision: v3.0.1
       OPAL release date: Mar 29, 2018
                 MPI API: 3.1.0
            Ident string: 3.0.1
                  Prefix: /opt/openmpi-3.0.1
 Configured architecture: armv7l-unknown-linux-gnueabihf
          Configure host: parallella2
           Configured by: parallella
           Configured on: Fri Apr 27 16:04:37 UTC 2018
          Configure host: parallella2
  Configure command line: '--prefix=/opt/openmpi-3.0.1/'
                          '--enable-mpirun-prefix-by-default'
                          '--enable-static'
                Built by: parallella
                Built on: Fri Apr 27 19:24:04 UTC 2018
              Built host: parallella2
              C bindings: yes
            C++ bindings: no
             Fort mpif.h: yes (all)
            Fort use mpi: yes (full: ignore TKR)
       Fort use mpi size: deprecated-ompi-info-value
        Fort use mpi_f08: yes
 Fort mpi_f08 compliance: The mpi_f08 module is available, but due to
                          limitations in the gfortran compiler and/or Open
                          MPI, does not support the following: array
                          subsections, direct passthru (where possible) to
                          underlying Open MPI's C functionality
  Fort mpi_f08 subarrays: no
           Java bindings: no
  Wrapper compiler rpath: runpath
              C compiler: gcc
     C compiler absolute: /usr/bin/gcc
  C compiler family name: GNU
      C compiler version: 4.9.3
            C++ compiler: g++
   C++ compiler absolute: /usr/bin/g++
           Fort compiler: gfortran
       Fort compiler abs: /usr/bin/gfortran
         Fort ignore TKR: yes (!GCC$ ATTRIBUTES NO_ARG_CHECK ::)
   Fort 08 assumed shape: yes
      Fort optional args: yes
          Fort INTERFACE: yes
    Fort ISO_FORTRAN_ENV: yes
       Fort STORAGE_SIZE: yes
      Fort BIND(C) (all): yes
      Fort ISO_C_BINDING: yes
 Fort SUBROUTINE BIND(C): yes
       Fort TYPE,BIND(C): yes
 Fort T,BIND(C,name="a"): yes
            Fort PRIVATE: yes
          Fort PROTECTED: yes
           Fort ABSTRACT: yes
       Fort ASYNCHRONOUS: yes
          Fort PROCEDURE: yes
         Fort USE...ONLY: yes
           Fort C_FUNLOC: yes
 Fort f08 using wrappers: yes
         Fort MPI_SIZEOF: yes
             C profiling: yes
           C++ profiling: no
   Fort mpif.h profiling: yes
  Fort use mpi profiling: yes
   Fort use mpi_f08 prof: yes
          C++ exceptions: no
          Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support: yes,
                          OMPI progress: no, ORTE progress: yes, Event lib:
                          yes)
           Sparse Groups: no
  Internal debug support: no
  MPI interface warnings: yes
     MPI parameter check: runtime
Memory profiling support: no
Memory debugging support: no
              dl support: yes
   Heterogeneous support: no
 mpirun default --prefix: yes
         MPI I/O support: yes
       MPI_WTIME support: gettimeofday
     Symbol vis. support: yes
   Host topology support: yes
          MPI extensions: affinity, cuda
   FT Checkpoint support: no (checkpoint thread: no)
   C/R Enabled Debugging: no
  MPI_MAX_PROCESSOR_NAME: 256
    MPI_MAX_ERROR_STRING: 256
     MPI_MAX_OBJECT_NAME: 64
        MPI_MAX_INFO_KEY: 36
        MPI_MAX_INFO_VAL: 256
       MPI_MAX_PORT_NAME: 1024
  MPI_MAX_DATAREP_STRING: 128
           MCA allocator: basic (MCA v2.1.0, API v2.0.0, Component v3.0.1)
           MCA allocator: bucket (MCA v2.1.0, API v2.0.0, Component v3.0.1)
           MCA backtrace: execinfo (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA btl: self (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA btl: tcp (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA btl: vader (MCA v2.1.0, API v3.0.0, Component v3.0.1)
            MCA compress: bzip (MCA v2.1.0, API v2.0.0, Component v3.0.1)
            MCA compress: gzip (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA crs: none (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                  MCA dl: dlopen (MCA v2.1.0, API v1.0.0, Component v3.0.1)
               MCA event: libevent2022 (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
               MCA hwloc: hwloc1117 (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
                  MCA if: linux_ipv6 (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
                  MCA if: posix_ipv4 (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
         MCA installdirs: env (MCA v2.1.0, API v2.0.0, Component v3.0.1)
         MCA installdirs: config (MCA v2.1.0, API v2.0.0, Component v3.0.1)
              MCA memory: patcher (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA mpool: hugepage (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                MCA pmix: isolated (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA pmix: pmix2x (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA pstat: test (MCA v2.1.0, API v2.0.0, Component v3.0.1)
              MCA rcache: grdma (MCA v2.1.0, API v3.3.0, Component v3.0.1)
               MCA shmem: mmap (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA shmem: posix (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA shmem: sysv (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA dfs: app (MCA v2.1.0, API v1.0.0, Component v3.0.1)
                 MCA dfs: orted (MCA v2.1.0, API v1.0.0, Component v3.0.1)
                 MCA dfs: test (MCA v2.1.0, API v1.0.0, Component v3.0.1)
              MCA errmgr: default_app (MCA v2.1.0, API v3.0.0, Component
                          v3.0.1)
              MCA errmgr: default_hnp (MCA v2.1.0, API v3.0.0, Component
                          v3.0.1)
              MCA errmgr: default_orted (MCA v2.1.0, API v3.0.0, Component
                          v3.0.1)
              MCA errmgr: default_tool (MCA v2.1.0, API v3.0.0, Component
                          v3.0.1)
              MCA errmgr: dvm (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA ess: env (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA ess: hnp (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA ess: pmi (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA ess: singleton (MCA v2.1.0, API v3.0.0, Component
                          v3.0.1)
                 MCA ess: tool (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA ess: slurm (MCA v2.1.0, API v3.0.0, Component v3.0.1)
               MCA filem: raw (MCA v2.1.0, API v2.0.0, Component v3.0.1)
             MCA grpcomm: direct (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA iof: hnp (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA iof: orted (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA iof: tool (MCA v2.1.0, API v2.0.0, Component v3.0.1)
            MCA notifier: syslog (MCA v2.1.0, API v1.0.0, Component v3.0.1)
                MCA odls: default (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA oob: tcp (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA plm: isolated (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA plm: rsh (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA plm: slurm (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA ras: simulator (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
                 MCA ras: slurm (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA rmaps: mindist (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA rmaps: ppr (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA rmaps: rank_file (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
               MCA rmaps: resilient (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
               MCA rmaps: round_robin (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
               MCA rmaps: seq (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA rml: oob (MCA v2.1.0, API v3.0.0, Component v3.0.1)
              MCA routed: binomial (MCA v2.1.0, API v3.0.0, Component v3.0.1)
              MCA routed: debruijn (MCA v2.1.0, API v3.0.0, Component v3.0.1)
              MCA routed: direct (MCA v2.1.0, API v3.0.0, Component v3.0.1)
              MCA routed: radix (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA rtc: hwloc (MCA v2.1.0, API v1.0.0, Component v3.0.1)
              MCA schizo: flux (MCA v2.1.0, API v1.0.0, Component v3.0.1)
              MCA schizo: ompi (MCA v2.1.0, API v1.0.0, Component v3.0.1)
              MCA schizo: orte (MCA v2.1.0, API v1.0.0, Component v3.0.1)
              MCA schizo: slurm (MCA v2.1.0, API v1.0.0, Component v3.0.1)
               MCA state: app (MCA v2.1.0, API v1.0.0, Component v3.0.1)
               MCA state: dvm (MCA v2.1.0, API v1.0.0, Component v3.0.1)
               MCA state: hnp (MCA v2.1.0, API v1.0.0, Component v3.0.1)
               MCA state: novm (MCA v2.1.0, API v1.0.0, Component v3.0.1)
               MCA state: orted (MCA v2.1.0, API v1.0.0, Component v3.0.1)
               MCA state: tool (MCA v2.1.0, API v1.0.0, Component v3.0.1)
                 MCA bml: r2 (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA coll: basic (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA coll: inter (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA coll: libnbc (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA coll: self (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA coll: sm (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA coll: sync (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA coll: tuned (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA fbtl: posix (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA fcoll: dynamic (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA fcoll: dynamic_gen2 (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
               MCA fcoll: individual (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
               MCA fcoll: static (MCA v2.1.0, API v2.0.0, Component v3.0.1)
               MCA fcoll: two_phase (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
                  MCA fs: ufs (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                  MCA io: ompio (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                  MCA io: romio314 (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA osc: sm (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA osc: pt2pt (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA osc: rdma (MCA v2.1.0, API v3.0.0, Component v3.0.1)
                 MCA pml: cm (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA pml: monitoring (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
                 MCA pml: ob1 (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA pml: v (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                 MCA rte: orte (MCA v2.1.0, API v2.0.0, Component v3.0.1)
            MCA sharedfp: individual (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
            MCA sharedfp: lockedfile (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)
            MCA sharedfp: sm (MCA v2.1.0, API v2.0.0, Component v3.0.1)
                MCA topo: basic (MCA v2.1.0, API v2.2.0, Component v3.0.1)
                MCA topo: treematch (MCA v2.1.0, API v2.2.0, Component
                          v3.0.1)
           MCA vprotocol: pessimist (MCA v2.1.0, API v2.0.0, Component
                          v3.0.1)

And:

> parallella@parallella2: bin $ mpif77 -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.9.3-13ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-multilib --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.3 (Ubuntu/Linaro 4.9.3-13ubuntu2) 
parallella@parallella2: bin $

**Comment by AndreasGocht** [comment]
From your error message:
```
/home/parallella/luca/scorep-4.0/build/build-mpi/libtool: line 10568: mpif77: command not found
```
This basically says, that `mpif77` is missing. According to your installation information from `ompi_info` openmpi is not installed at the standard location. It is in `/opt/openmpi-3.0.1`. Please be sure to add the `bin` directory of `/opt/openmpi-3.0.1` to the `PATH`. most likely doing something like
```
export PATH=/opt/openmpi-3.0.1/bin:$PATH
../configure --enable-shared --with-mpi=openmpi --with-nocross-compiler-suite=gcc
```
Moreover please be sure to have gfortran installed.

I am not an expert in ARM based systems. You might want to contact the scorep support mailing list for more specific help about installing Score-P on ARM.

Best,

Andreas

**Comment by jungla88** [comment]
Thank you. I'll report this to scorep support.
