### ISSUE TITLE
Cannot run test-case in Taurus

### ISSUE THREAD

**Issue by Rigel-Alves** [score-p/scorep_binding_python#111]
Hi,

I am having problems to use the `scorep_binding_python` in the HPC cluster _Taurus_. `pip show scorep` shows that the python module is correctly installed and `python -c 'import scorep'` has no output, but if I try to run the first test-case:

`python -m scorep test_sleep.py`

I get the following error message:

```
ERROR: ld.so: object 'libscorep_init_subsystem-3.7.so' from LD_PRELOAD cannot be preloaded: ignored.
/home/alves/dlr/flowsim_builder/install/python/python_3_7_4_gcc_system/bin/python: symbol lookup error: /sw/installed/Score-P/6.0-gompi-2019a/lib/libscorep_measurement.so: undefined symbol: scorep_subsystems
```

Score-P comes from a Taurus module (`Score-P/6.0-gompi-2019a`), which is installed with the all the necessary prerequisites (`--enable-shared` and _GCC plugin_). `Python`(3), `pip` and the `scorep_binding_python` on their turn are installed by a DLR script. The goal is to use the Score-P module with DLR simulation codes written in Python, so I need to use their scripts to install Python and its related dependencies.

Could you help me figure out what is going on?

Thank you very much,

**Comment by AndreasGocht** [comment]
Hey Rigel,

is it possible that you run `python -m scorep test_sleep.py` from the login node on Taurus? This leads sometimes to Issues with wired access rights to `/tmp`.

Please try to run the test in a Job, like:

`srun -p interactive -c 1 -n 1 - t --time=0:10:00 python -m  scorep test_sleep.py`

Best,

Andreas

**Comment by Rigel-Alves** [comment]
Thanks Andreas. I was indeed using the login node. With srun, it works in serial:

`srun -n 1 --ntasks-per-node 1 -o %j-%t.cout -e %j-%t.cerr -p haswell --mem-per-cpu 2583 python -m scorep test_sleep.py`

But in parallel (with 2 ranks):

`srun -n 2 --ntasks-per-node 2 -o %j-%t.cout -e %j-%t.cerr -p haswell --mem-per-cpu 2583 python -m scorep test_sleep.py`

One of them fails with the following output:

`[Score-P] src/measurement/scorep_runtime_management.c:334: Error: File does already exist: POSIX: Can't create experiment directory "/home/h9/alves/dlr/flowsim_builder/install/build/scorep_binding_python/scorep_binding_python-3.0/test/scorep-measurement-tmp".`

I clean the working directory (of the outputs of the previous attempt) before resubmitting the job. Do you know what is causing this new error?

**Comment by AndreasGocht** [comment]
Jip. you did not specify `--mpp=mpi`, e.g. as documented please use:

`python -m scorep --mpp=mpi --thread=pthread <script.py>`

Moreover, I am not sure if the test_sleep.py works with MPI. But there should also be an mpi4py test. As the inital issue is solved, I'll close the ticket. If you do have any furhter Issues, please open a new one.

Best,

Andreas
