### ISSUE TITLE
undefined symbol: SCOREP_MutexUnlock

### ISSUE THREAD

**Issue by NormanTUD** [score-p/scorep_binding_python#118]
Hi,
I'm a total beginner with Score-P and may do some things wrong. But I did this:

- Go to Tauruslogin5
- Load module TensorFlow on Taurus (but it's the same with Python/3.6.6-fosscuda-2018b)
- Download the current python bindings, install them with "pip3 install --user ."
- Wrote this simple test script (according to the wiki https://github.com/score-p/scorep_binding_python ) as `test.py`:

```
import numpy as np
import scorep

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

with scorep.instrumenter.enable():
    c = np.dot(a,b)
```
- Loaded Score-P with "ml Score-P"
- did `python3 -m scorep --noinstrumenter test.py`

But it doesn't work and only displays this error:

```
ERROR: ld.so: object 'libscorep_init_subsystem-3.7.so' from LD_PRELOAD cannot be preloaded: ignored.
/sw/installed/Python/3.7.4-GCCcore-8.3.0/bin/python3: symbol lookup error: /sw/installed/Score-P/6.0-iimpi-2020a/lib/libscorep_measurement.so: undefined symbol: SCOREP_MutexUnlock
```

Similiar with ml Python/3.6.6-fosscuda-2018b:

```
ERROR: ld.so: object 'libscorep_init_subsystem-3.6.so' from LD_PRELOAD cannot be preloaded: ignored.
/sw/installed/Python/3.6.6-fosscuda-2018b/bin/python3: symbol lookup error: /sw/installed/Score-P/6.0-iimpi-2020a/lib/libscorep_measurement.so: undefined symbol: SCOREP_MutexUnlock
```

It is not obvious to me that I do something wrong, though this might be the result of my lack of expertise on Score-P. Anything I do wrong, or is it even possible to get the error messages more detailled?

Thanks!

**Comment by NanoNabla** [comment]
You're Score-P seems to be compiled with Intel, your Python with FossCuda. Try using module `Score-P/6.0-gompic-2019b`. 

Moreover, use the compute nodes instead of login nodes due to limitations on `tauruslogin`

**Comment by NormanTUD** [comment]
@NanoNabla Ahhh yes, now it works. Sorry. And thanks!
