### ISSUE TITLE
pip install fails when Score-P was configured '--without-mpi'

### ISSUE THREAD

**Issue by knuedd** [score-p/scorep_binding_python#12]
MPI seems to be hardwired and installation fails when Score-P 4.0 comes without MPI. I stumbled upon this on my Raspi first. But I could reproduce it on my Linux laptop just the same.

With Score-P I did `../configure --prefix=/home/knue/local/score-p --without-cube --enable-shared; make; make install`. Then I used this Score-P for `pip install .` and everything went okay.

When I add `--without-mpi` to Score-P's configure and do everything else just the same, then the `pip install .` fails at "building 'scorep.scorep_bindings_mpi' extension".

I hope this is not too complicated. Thanks for looking into this issue!

Andreas

**Comment by AndreasGocht** [comment]
Should be fixed with the current master.
