### ISSUE TITLE
'tpd == 0' error

### ISSUE THREAD

**Issue by metyr** [score-p/scorep_binding_python#15]
Hi, 

I meet this error from time to time on profiling various python scripts:

[Score-P] src/measurement/thread/create_wait/scorep_thread_create_wait_pthread.c:89: Fatal: Bug 'tpd == 0': Invalid Pthread thread specific data object. Please ensure that all pthread_create calls are instrumented.

Is there a solution fix it? Thanks.

Regards,
Rui

**Comment by AndreasGocht** [comment]
Hey,

looks like your Score-P version cannot work with orphen threads. Which version do you use? Please try the latest trunk version from:
http://scorepci.pages.jsc.fz-juelich.de/scorep-pipelines/

Best,

Andreas

**Comment by metyr** [comment]
Hi Andreas,

Many thanks for your reply. By following your suggestion I installed the latest trunk version of score-p. The previous issue was indeed solved but it runs into some other issues as below:

bash-4.1$ mpirun -np 1  python -m scorep --mpi test.py
Traceback (most recent call last):
  File "/apps/python/2.7.11/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/apps/python/2.7.11/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/apps/scorep_py27/r13798_libwrap_ompi_3.0.1/lib/python2.7/site-packages/scorep/__main__.py", line 149, in <module>
    main()
  File "/apps/scorep_py27/r13798_libwrap_ompi_3.0.1/lib/python2.7/site-packages/scorep/__main__.py", line 141, in main
    global_trace.runctx(code, globs, globs)
  File "/apps/scorep_py27/r13798_libwrap_ompi_3.0.1/lib/python2.7/site-packages/scorep/trace.py", line 57, in runctx
    exec(cmd, globals, locals)
  File "test.py", line 9, in <module>
    import UWgmic as geo
  File "/apps/UWgmic/UWgmic/__init__.py", line 8, in <module>
    raise ImportError("Can not find module_uw, please check your installation")
ImportError: Can not find module_uw, please check your installation
python: ../src/measurement/paradigm/mpi/scorep_ipc_mpi.c:230: SCOREP_IpcGroup_GetRank: Assertion `SCOREP_Status_IsMppInitialized()' failed.

Without using scorep module, the command "mpirun -np 1  python  test.py" runs OK. I also tried to manually insert the module_uw module location into the code via sys.path.insert but it still doesn't work. 

Am I missing some settings to keep other modules taking effect after using scorep module? 

Regards,
Rui

**Comment by AndreasGocht** [comment]
Hey Rui,

> Am I missing some settings to keep other modules taking effect after using scorep module?

Nothing I am aware of. However, it might be that there is a clush around the way you invoke your program, and the scorep setup is done. Can you please post the code of `_run_code` and `_run_module_as_main`?

just for completes: There are two separate errors here: the first one is the python import failure. The second one is the assertion thrown by Score-P. The assertion fires presumably because the code finishes, due to an exception, without initialising MPI. As you run with `--mpi` Score-P needs this initialisation to happen in order to synchronise the different traces at the end.

Best,

Andreas

**Comment by metyr** [comment]
Hi Andreas,

It proves the issue was caused by building my python modules and scorep with different GCC versions so there is glibc conflicts between the module and scorep. After making them consistent it works. I should have checked it in advance!

Many thanks for your making such useful binding tool to enable scorep on profiling python code. 

Regards,
Rui

**Comment by AndreasGocht** [comment]
You are welcome :smile:

Best,

Andreas
