### ISSUE TITLE
Publish Version 4.1.1 to PyPi

### ISSUE THREAD

**Issue by maximilian-tech** [score-p/scorep_binding_python#152]
The current version on PyPi is 4.1.0 which is not compatible with Score-P 8.0. 
It should therefore be updated to Version 4.1.1.

**Comment by AndreasGocht** [comment]
This was more work than expected. Mostly updating the CI infrastructure. However, with #154 merged, I'll publish a new release.

**Comment by AndreasGocht** [comment]
Done.
