### ISSUE TITLE
Function calls in user regions not separated

### ISSUE THREAD

**Issue by elwer** [score-p/scorep_binding_python#164]
When I have the following code, the function calls in the user region are not separated from the ones outside the user region for the exclusive time metric.  I am not sure if that is the expected behavior or a bug. If it's expected, is there a way I can separate the two, or do I need to look at the call stack and the inclusive time?

```
import scorep
import scorep.user
from time import sleep

def foo():
    sleep(5)

foo()
with scorep.user.region("bar")
    foo()
    foo()
```

![grafik](https://github.com/score-p/scorep_binding_python/assets/9395556/f82a7bda-0b75-4347-8a3c-8f720b9c79c6)

**Comment by bertwesarg** [comment]
What do you mean with "separated"? The _Function Summary_ in Vampir is a _flat profile_. If you want a _call-path profile_ use the _Call Tree_ chart.

**Comment by elwer** [comment]
Thanks for the clarification! The call tree is indeed what I am looking for.
