### ISSUE TITLE
mkdtemp Python version dependence

### ISSUE THREAD

**Issue by mpokorny** [score-p/scorep_binding_python#20]
The `tempfile.mkdtemp()` interface changed subtly in Python 3.5, causing a failure at https://github.com/score-p/scorep_binding_python/blob/d990d002af0c4b60a9f04a33ca557a068a6b43d1/scorep/subsystem.py#L55 when using Python 2.7. The first argument must be an empty string rather than a `None` value to get the default temporary directory `suffix` value for earlier versions of Python.

**Comment by AndreasGocht** [comment]
Thanks for the hint. I fixed it.

Best,

Andreas

**Comment by AndreasGocht** [comment]
ref 46c5cbda916975ff4ddb6a6d81cade9b94d33b3c
