### ISSUE TITLE
Profiling Tensorflow ( out of memory error)

### ISSUE THREAD

**Issue by abidmalikwaterloo** [score-p/scorep_binding_python#23]
I am profiling tensorflow+MPI using scorep binding for python. I am using 4 nodes using MPI. I am getting out of memory error. I  tried with SCOREP_TOTAL_MEMORY=16384000 as well. Even then it is giving me out of memory error and asking to increase the number. What should be the safe number?
 I am using a simple NNet. I am planning to test this with 3D GANs.

[5779.pdf](https://github.com/score-p/scorep_binding_python/files/2818387/5779.pdf)
[script.pdf](https://github.com/score-p/scorep_binding_python/files/2818388/script.pdf)

**Comment by AndreasGocht** [comment]
Please have a look to the Documentation:

https://www.vi-hps.org/projects/score-p/

you might want to specify

```
export SCOREP_TOTAL_MEMORY=3G
```

Best,

Andreas

**Comment by abidmalikwaterloo** [comment]
@AndreasGocht Thanks it works. I  need to read the document first.
