### ISSUE TITLE
--keep-files option does not seem to work

### ISSUE THREAD

**Issue by pierretr** [score-p/scorep_binding_python#26]
When using --keep-files options as in the following command:
`/usr/bin/python -m scorep --mpp=mpi --openmp --thread=omp --compiler --keep-files test.py`

The following error is raised:
```
<path_to_scorep_binding_python>/install/lib/python2.7/site-packages/scorep/helper.py", line 77, in generate_compile_deps
    "given config {} is not supported".format(config))
ValueError: given config ['--mpp=mpi', '--openmp', '--thread=omp', '--compiler', '--keep-files', '--compiler'] is not supported
```

"--keep-files" seems to be added to scorep_config options which is used as arguments to call scorep-config that does not recognize --keep-files as an option.

**Comment by AndreasGocht** [comment]
Fixed. Thanks for the report.

Best,

Andreas
