### ISSUE TITLE
List dependencies in README.

### ISSUE THREAD

**Issue by harryherold** [score-p/scorep_binding_python#28]
Could you please list in the README.md the require software dependencies.

**Comment by harryherold** [comment]
e.g.
```
print("LD_PRELOAD is already specified. If Score-P is already loaded this might lead to errors.", file=sys.stderr)
                                                                                                          ^
SyntaxError: invalid syntax
```
Not Python2 compatible.

**Comment by AndreasGocht** [comment]
python2 should work. It looks like the doc is a little bit wrong here:

https://stackoverflow.com/questions/24233598/function-to-write-on-stderr-with-python2-and-python3?rq=1

I'll fix this as soon, as I find the time.

Best,

andreas

**Comment by harryherold** [comment]
Yes and CMake is also a dep.

**Comment by AndreasGocht** [comment]
CMake should not be a dependency any more. Not in the v1.0 release.

Best,

Andreas
