### ISSUE TITLE
Location of Score-P IO branch

### ISSUE THREAD

**Issue by tyohei** [score-p/scorep_binding_python#3]
I'm trying to use Score-P binding Python with a code that contains multithreading modules.
I failed to profile my code when I added threading with it.

Since README says *Please have a look to the Score-P IO branch*, I googled for a `Score-P IO branch` but couldn't find some valuable information.

So, my questions are, is it possible to use this binding with multithreading module? and where can I find Score-P IO Branch?

Thanks

**Comment by AndreasGocht** [comment]
Hey

unfortunately the Score-P IO branch is still in development and not official released yet. Please contact support@score-p.org . They Score-P team might be able to grant you access to the branch. 

Best,

Andreas

**Comment by AndreasGocht** [comment]
Please have a look to http://scorepci.pages.jsc.fz-juelich.de/scorep-pipelines/

The Score-P group decided to publish the current trunk sources. The current trunk provides thread support.

Best,

Andreas
