### ISSUE TITLE
context manager for disabling instrumentation

### ISSUE THREAD

**Issue by tilsche** [score-p/scorep_binding_python#34]
```
with scorep.disable_instrumentation():
    # code I don't want to see every function invocation for
```

**Comment by tilsche** [comment]
I feel like `scorep.user.disable()` sounds like disabling **user** instrumentation - but I'm focusing on disabling the **automatic** instrumentation while retaining user instrumentation. Although I would understand there are different use cases. Maybe even something like

    with scorep.instrumentation(user=True, automatic=False):

**Comment by AndreasGocht** [comment]
Disabling user instrumentation is currently not possible, and I am not sure if I'd like to provide this functionality ...
However something like:
```
with scorep.instrumenter.enable():
    pass
```
or 
```
with scorep.instrumenter.disable():
    pass
```
seems to be reasonable. Aka using the `instrumenter` as a module to configure the instrumentation of the python code. Or shall we call it `adapter` to stay in Score-P terminology?

**Comment by AndreasGocht** [comment]
The branch `issue-#34` implements these contexts. I didn't add the user parameter thing, as I am not sure there is a point in doing so.

Best,

Andreas
