### ISSUE TITLE
provide dummy calls for non-scorep runs

### ISSUE THREAD

**Issue by tilsche** [score-p/scorep_binding_python#35]
It would be very useful if I could use user instrumentation etc. of the scorep module unconditionally in applications. The code would then just be empty dummies. This would allow to develop applications with user instrumentation in mind without having to deal with conditionally enabling it.

**Comment by AndreasGocht** [comment]
Please have a look at the `dummy_user` branch. If you do not use `-m scorep` the user instrumentation should do nothing.
