### ISSUE TITLE
SCOREP_FILTERING_FILE support

### ISSUE THREAD

**Issue by jgphpc** [score-p/scorep_binding_python#38]
Hi,

Does scorep_binding_python support $SCOREP_FILTERING_FILE ?
Something like (no c++):

```
SCOREP_FILE_NAMES_BEGIN
  EXCLUDE *
  INCLUDE sub_func.py
SCOREP_FILE_NAMES_END
```

**Comment by AndreasGocht** [comment]
Hey,

yes, filtering using a filter file is supported. However, I am not sure if filtering by file will work. I would suppose to filter per module (i.e. region), e.g.:
```
SCOREP_REGION_NAMES_BEGIN
EXCLUDE *
INCLUDE __main__:*
                some_other_module:*
                some_other_module2:specific_function
SCOREP_REGION_NAMES_END
```
Please be aware that the effect on the runtime might be rather small, as the python tracing interface is still invoked.
If you are trying to reduce the instrumentation overhead, I recommend looking at the branch `issue-#34` (related to #34 ). We are currently implementing context managers, which will allow disabling the instrumentation for specific regions. This feature will be part of the 2.0 release of the python bindings.

Best,

Andreas

**Comment by AndreasGocht** [comment]
I just double-checked with a colleague: Filtering by filename should also be possible, but I never tested it.

Best,

Andreas
