### ISSUE TITLE
Avoid malloc during region_enter

### ISSUE THREAD

**Issue by AndreasGocht** [score-p/scorep_binding_python#42]
@harryherold noted, that the malloc might be expensive.

**Comment by AndreasGocht** [comment]
659df5019f617c87580efb9fdeaa00b4ed7f45a0 might fix this. Threading might be a problem.

**Comment by harryherold** [comment]
Yes, threading could be an issue. I would also avoid the allocation in the `region_end`. I prefer a solution with a array within the data segment:
```
char region_buffer[region_buffer_max];
assert((strlen(module) + strlen(region_name)) < region_buffer_max &&
"Resulting region is too long\n");
sprintf(region_buffer, "%s:%s", module, region_name);
```
I will provide a pull request soon.

**Comment by AndreasGocht** [comment]
@harryherold would the use of [alloca](http://man7.org/linux/man-pages/man3/alloca.3.html) solve your problem?
@tilsche @bmario what do you think?

Best,

Andreas

**Comment by harryherold** [comment]
I am fine with 659df50 because the rest of the code is also not thread safe.

**Comment by AndreasGocht** [comment]
True. I just realised that the GIL is never released. So there is no need to think about thread-safety.
