### ISSUE TITLE
undefined symbol when using --thread=omp

### ISSUE THREAD

**Issue by jdomke** [score-p/scorep_binding_python#46]
Hi,

running `python3.7 -m scorep --thread=pthread ./a.py` of very simple hello world script works, but when I add `--thread=omp` then it fails with:
/scr0/jens/spack/opt/spack/linux-centos7-x86_64/gcc-9.1.0/python-3.7.3-civ2iiqopzfrzuhnit4hpexjlm4uwp5b/bin/python3.7: symbol lookup error: /scr0/jens/spack/opt/spack/linux-centos7-x86_64/gcc-9.1.0/scorep-6.0-kb66d72rn7wt5lxoige6qjoyrmpynvwr/lib/libscorep_adapter_opari2_openmp_mgmt.so.8: undefined symbol: POMP2_Get_num_regions

(using scorep@6.0 and opari2@2.0.5)

**Comment by AndreasGocht** [comment]
It is fixed in master. The fix will be in version 2.1 also.

Best,

Andreas
