### ISSUE TITLE
some numpy functions don't have an associated region

### ISSUE THREAD

**Issue by AndreasGocht** [score-p/scorep_binding_python#63]
Some Numpy regions end up having the name `None:foo`, which is misleading, as @harryherold pointed out. However, this seems to be related to some newer Numpy wrapper function.

One proposal is to simply avoid `None:` and only report `foo`. However, I am not relay happy, as this leads to confusion with c functions aka `void foo();`. Another option would be to report `:foo`. 

The best would be to detect thats foo is a numpy function. Any proposals are welcome.

**Comment by AndreasGocht** [comment]
https://github.com/numpy/numpy/blob/4753652c605833e2398d7e46b754a71729a54713/numpy/core/multiarray.py#L705

**Comment by AndreasGocht** [comment]
see brach issue-63

looks like we are dealing with python internals here.
See:
[functools](https://docs.python.org/3/library/functools.html)
`code.co_filename = <__array_function__ internals>`

**Comment by AndreasGocht** [comment]
And the related [NEP-18](https://numpy.org/neps/nep-0018-array-function-protocol.html)

**Comment by AndreasGocht** [comment]
Ok. As it seems the  `<__array_function__ internals>` is numpy / numpy world specific. What I can do is to check for this, and then manually set the region to numpy. Alternatively, we could call the region `<__array_function__ internals>:dot` .
Any suggestions?

**Comment by AndreasGocht** [comment]
Or a combination of both, aka `numpy.__array_function__:dot`. My current favourit.

**Comment by harryherold** [comment]
I agree `numpy.__array_function__:dot` seems to be the best candidate. It contains more implementation details and a standard python user is able to find his called functions.

**Comment by AndreasGocht** [comment]
Fixed.
