### ISSUE TITLE
Dummy instrumenter has faulty runfunc and run functions

### ISSUE THREAD

**Issue by Flamefire** [score-p/scorep_binding_python#76]
They do literally nothing instead of calling the given code/function. So either those should be removed, replaced by a run function which dispatches based on the type of the passed object (function or code) or implemented. The current solution does not adhere to "code runs just without instrumentation"-principle

**Comment by AndreasGocht** [comment]
If I remember correctly, we already agreed on merging `run` and `runctx`. Moreover, I am happy to remove runfunc.
