### ISSUE TITLE
Handling of "expected" region exists w/o enter (e.g. threading)

### ISSUE THREAD

**Issue by Flamefire** [score-p/scorep_binding_python#87]
I added tests for using the module with Pythons builtin `threading` lib which simply creates 2 `Thread`s and runs a test function in each of them. The tests fail due to region exit events without a region enter which is expected.

What happens is:
- `threading.settrace(func)` is called (by scorep) to notify the threading module about the trace function
- the `Thread.start` method spawns a new thread which executes a `_bootstrap` method (which calls a `_bootstrap_inner` method)
- `sys.settrace(func)` is called (by threading) to install the trace function in the new thread
- now the user-defined function is run the new thread
- the 2 `_bootstrap` methods return leading to the exit-without-enter issue

Given that there is no way to avoid this I'd propose to simply ignore the error in the `region_end` function for known region names. And add `threading:_bootstrap_inner` and `threading:_bootstrap` to those.

Additionally I'd also ignore errors for regions starting with `_pydev_bundle.pydev_monkey` which occur e.g. when debugging in VisualStudioCode.

**Comment by AndreasGocht** [comment]
Actually, https://github.com/score-p/scorep_binding_python/blob/07f3e09e1c121a195fe4f2f8c18d38bf542af3ac/src/scorepy/events.cpp#L43 should take care of this situation, i.e. it is supposed to realise, that the function (`_bootstrap`) has not been seen before, add an `error_region`, and then ignore the function. I just wonder why this does not happen?

Probably, `_bootstrap` is called before, so it is known, i.e. in the hash map, but not entered. So adding a check if a region is entered might help here. What do you think?

**Comment by Flamefire** [comment]
Sorry I should have been more clear: The test tests for `std_err == ""` as the other tests do. This check fails because the handling you mentioned kicks in and prints to stderr.

My proposal was to exclude certain expected failures from that handling to not confuse users which will then also make the above check pass.

**Comment by AndreasGocht** [comment]
Hmm ... I am not convinced. First: The more modules and functions we have to check for, the more overhead we get. Second: We hide more details from the user. I need to inspect the functions to see what else they are doing and if it might be relevant.

**Comment by Flamefire** [comment]
> The more modules and functions we have to check for, the more overhead we get. 

True, but this happens in the case where a region begin is not found which is very rare. In this case it happens at the end of a thread where increased overhead might not be a problem

> We hide more details from the user.

While this is true I don't think providing an error region and message everytime a user uses a thread without any way to avoid this gives any value. I'm sure it's only a matter of time a bug report of a confused user pops up here relating to that and what to do about this. As in this case there is nothing one can do we could as well suppress the error.

> I need to inspect the functions to see what else they are doing and if it might be relevant.

IMO it isn't, but even if it was: It is impossible to trace this function because the tracing is enabled IN this function So an ENTER event can never occur.

**Comment by AndreasGocht** [comment]
> True, but this happens in the case where a region begin is not found which is very rare. In this case it happens at the end of a thread where increased overhead might not be a problem

I just realised that you would like to add this check during the creation of the error region. 

However, what about putting this the other way around? E.g. by adding the missing region begin during the setup of threaded tracing?

**Comment by Flamefire** [comment]
I think this won't work:
1. You don't get the setup as an event to handle. This is done internally by Python which calls `sys.settrace` and then continues processing. The tracer then gets regular events as in the single-thread case. You only notice the missing region at the end of the thread
2. I don't see how you'd be able to create a region definition given that you have neither the name nor the line number of the function available in general. This is why I proposed using a "Whitelist" of function names so if another function is used we still get the error and can decide if we want to add it to the whitelist. But we can't know for sure in all situations and all thread libs (I understand there are multiple, e.g. "greenlet" or so) what that function is called.

Another Idea I just had: Why does this not happen when we enable tracing? I mean what happens is:
```
something()
  _enable_instrumenter()
    call_c_function() --> Calls PyEvalSetTrace
    maybe_call_threading.settrace
```

With this we are also exiting `something` or at least `_enable_instrumenter` so that should appear in the trace as an error shouldn't it? It does not so there must be something which we might be able to use to avoid the exit events for the _bootstrap functions altogether

**Comment by Flamefire** [comment]
>  Why does this not happen when we enable tracing? 

Found: This does indeed occur as in: Trace RETURN events are generated for the functions that enabled the tracer. However they are explicitly ignored via https://github.com/score-p/scorep_binding_python/blob/9b05409fa05283ab6612e58542a3b66e678b2005/scorep/_instrumenters/scorep_profile.py#L49 checking for the module name

**Comment by AndreasGocht** [comment]
I just wonder how that did happen XD. But what has trace to do with `_usetprofile`?

**Comment by Flamefire** [comment]
> I just wonder how that did happen XD

What do you mean?

> But what has trace to do with _usetprofile?

That's the function used to disable the profile: https://github.com/score-p/scorep_binding_python/blob/9b05409fa05283ab6612e58542a3b66e678b2005/scorep/_instrumenters/scorep_profile.py#L21

Back to topic: Any other idea or shall I add a whitelist for allowed missing region exits?   
An alternative I've seen used by others: For every CALL event there is a RETURN event, except of course for those entered before tracing started. Hence I'd change the (C-)Instrumenter to store the last entered code and ignore all RETURN events which do not match previously handled CALL events (yes that's going to be a stack and it's got to be per thread). But this forces us to also handle a previously ignored case: What about regions begin w/o a region end? Those can happen when the instrumenter is disabled. Keeping a stack of previously entered regions allows us to handle this somehow. I guess currently the call stack will be very messy when the instrumenter is disabled for a bit.

**Comment by AndreasGocht** [comment]
> What do you mean?

never mind.

> That's the function used to disable the profile: 

jip, but what does it have to do with trace? 

> Back to topic: Any other idea or shall I add a whitelist for allowed missing region exits?

Nope. whitelist is till now the best. Please go ahead.

**Comment by Flamefire** [comment]
> jip, but what does it have to do with trace?

Names... "Trace" as in "Trace event" so in the sense of Score-P. The Trace instrumenter and Profile instrumenter generate trace events by listening for Python trace or profile events. Damn...
